### ISSUE TITLE
求帮忙检查并合并一下DarkPlusConcise插件~~

### ISSUE THREAD

**Issue by APigggggg** [zuoez02/siyuan-plugins#26]
Dark+作为主题功能强大，不过有不少人希望能让Dark+的外观更加简洁。

我自己弄了一些代码片段，如果直接贴在论坛里并不方便大家寻找；

如果再基于Dark+建个新主题，考虑到萌新大佬的更新频率，维护起来太费劲了。

想了想还是希望作为插件放在插件商店里。

已经写好并提交pr了\~\~第一次提交pr，不是很懂流程，求帮忙看下有没有哪里要改的\~\~如果问题不大的话就麻烦合并一下啦\~\~

**Comment by zuoez02** [comment]
在PR的conversation里面讨论就可以了，这个issue关掉了
